apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-native-webflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-native-webflux
  template:
    metadata:
      labels:
        app: spring-native-webflux
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: api
          image: luciferino90/spring-native-webflux:0.0.5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-native-webflux
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: spring-native-webflux
spec:
  type: ClusterIP
  ports:
    - name: spring-native-webflux
      port: 8080
  selector:
    app: spring-native-webflux
