apiVersion: apps/v1
kind: Deployment
metadata:
  name: native-demo-deployment
  labels:
    app: native-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: native-demo
  template:
    metadata:
      labels:
        app: native-demo
    spec:
      containers:
        - name: native-demo
          image: luciferino90/native-demo:0.0.3
          ports:
            - containerPort: 80
